# Generated by Django 5.2.7 on 2025-11-13 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_ranksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='student_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.student'),
        ),
    ]
