# Generated by Django 5.2.8 on 2025-11-22 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_task_student_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='student_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_tasks', to='Students.student'),
        ),
    ]
